### ISSUE TITLE
List number formatting 

### ISSUE THREAD

**Issue by cormullion** [pat-alt/quarto-julia#4]
Looks really good with the font improvements!

One minor nitpick - list number formatting:

<img width="287" alt="Screenshot 2024-06-19 at 16 36 29" src="https://github.com/pat-alt/quarto-julia/assets/52289/29b5b011-6ac8-4578-bbf2-fddd54048ba5">

**Comment by pat-alt** [comment]
Thanks for flagging, no idea what happened there! This is fixed now: https://www.patalt.org/quarto-julia-website/examples/basic_formats/revealjs/
